from mistyPy import Robot

misty = Robot("192.168.0.11")
print(misty.getImageList())

"['celebration.jpg', 'e_Admiration.jpg', 'e_Aggressiveness.jpg', 'e_Amazement.jpg', 'e_Anger.jpg', 'e_ApprehensionConcerned.jpg', 'e_Contempt.jpg', 'e_ContentLeft.jpg', 'e_ContentRight.jpg', 'e_DefaultContent.jpg', 'e_Disgust.jpg', 'e_Disoriented.jpg', 'e_EcstacyHilarious.jpg', 'e_EcstacyStarryEyed.jpg', 'e_Fear.jpg', 'e_Grief.jpg', 'e_Joy.jpg', 'e_Joy2.jpg', 'e_JoyGoofy.jpg', 'e_JoyGoofy2.jpg', 'e_JoyGoofy3.jpg', 'e_Love.jpg', 'e_Rage.jpg', 'e_Rage2.jpg', 'e_Rage3.jpg', 'e_Rage4.jpg', 'e_RemorseShame.jpg', 'e_Sadness.jpg', 'e_Sleeping.jpg', 'e_SleepingZZZ.jpg', 'e_Sleepy.jpg', 'e_Sleepy2.jpg', 'e_Sleepy3.jpg', 'e_Sleepy4.jpg', 'e_Surprise.jpg', 'e_SystemBlackScreen.jpg', 'e_SystemBlinkLarge.jpg', 'e_SystemBlinkStandard.jpg', 'e_SystemCamera.jpg', 'e_SystemFlash.jpg', 'e_SystemGearPrompt.jpg', 'e_SystemLogoPrompt.jpg', 'e_Terror.jpg', 'e_Terror2.jpg', 'e_TerrorLeft.jpg', 'e_TerrorRight.jpg', 'photoSaveTest.jpg.jpg', 'shaq.jpg']"

print(misty.getAudioList())

"['11_temp_output_audio.wav', '13_temp_output_audio.wav', '15_temp_output_audio.wav', '16_temp_output_audio.wav', '18_temp_output_audio.wav', '2_temp_output_audio.wav', '20_temp_output_audio.wav', '27_temp_output_audio.wav', '29_temp_output_audio.wav', '32_temp_output_audio.wav', '39_temp_output_audio.wav', '42_temp_output_audio.wav', '6_temp_output_audio.wav', 'capture_HeyMisty.wav', 'gtcu-9f721d01-21eb-4f4f-99fb-36417a12ba0e.wav', 's_Acceptance.wav', 's_Amazement.wav', 's_Amazement2.wav', 's_Anger.wav', 's_Anger2.wav', 's_Anger3.wav', 's_Anger4.wav', 's_Annoyance.wav', 's_Annoyance2.wav', 's_Annoyance3.wav', 's_Annoyance4.wav', 's_Awe.wav', 's_Awe2.wav', 's_Awe3.wav', 's_Boredom.wav', 's_Disapproval.wav', 's_Disgust.wav', 's_Disgust2.wav', 's_Disgust3.wav', 's_DisorientedConfused.wav', 's_DisorientedConfused2.wav', 's_DisorientedConfused3.wav', 's_DisorientedConfused4.wav', 's_DisorientedConfused5.wav', 's_DisorientedConfused6.wav', 's_Distraction.wav', 's_Ecstacy.wav', 's_Ecstacy2.wav', 's_Fear.wav', 's_Grief.wav', 's_Grief2.wav', 's_Grief3.wav', 's_Grief4.wav', 's_Joy.wav', 's_Joy2.wav', 's_Joy3.wav', 's_Joy4.wav', 's_Loathing.wav', 's_Love.wav', 's_PhraseByeBye.wav', 's_PhraseEvilAhHa.wav', 's_PhraseHello.wav', 's_PhraseNoNoNo.wav', 's_PhraseOopsy.wav', 's_PhraseOwOwOw.wav', 's_PhraseOwwww.wav', 's_PhraseUhOh.wav', 's_Rage.wav', 's_Sadness.wav', 's_Sadness2.wav', 's_Sadness3.wav', 's_Sadness4.wav', 's_Sadness5.wav', 's_Sadness6.wav', 's_Sadness7.wav', 's_Sleepy.wav', 's_Sleepy2.wav', 's_Sleepy3.wav', 's_Sleepy4.wav', 's_SleepySnore.wav', 's_SystemCameraShutter.wav', 's_SystemFailure.wav', 's_SystemSuccess.wav', 's_SystemWakeWord.wav', 'testing1.wav']"
